name: mamba
description: A small side project to allow for teams to size tickets using Story Point cards. This is intended for the SCRUM Agile methodology. 

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  flutter_spinkit: ^5.1.0
  universal_io: ^2.0.4
  web_socket_channel: ^2.1.0
  uuid: ^3.0.6
  flutter_bloc: ^8.0.1
  modal_bottom_sheet: ^2.0.1
  shared_preferences: ^2.0.13
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/cards/
