name: mamba
description: A small side project to allow for teams to size tickets using Story Point cards. This is intended for the SCRUM Agile methodology.

publish_to: 'none'

version: 2.2.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.4
  json_annotation: ^4.5.0
  flutter_spinkit: ^5.1.0
  universal_io: ^2.0.4
  web_socket_channel: ^2.2.0
  uuid: ^3.0.6
  modal_bottom_sheet: ^2.0.1
  shared_preferences: ^2.0.15
  app_links: ^3.2.0
  qr_flutter: ^4.0.0
  collection: ^1.16.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  test: ^1.21.1

flutter:
  uses-material-design: true

  assets:
    - images/
