name: mamba
description: A simple app that allows development teams to size tickets using Story Point cards. This is intended for the SCRUM Agile methodology making use of story points.

publish_to: 'none'

version: 3.1.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  json_annotation: ^4.8.0
  flutter_spinkit: ^5.1.0
  universal_io: ^2.0.4
  universal_html: ^2.2.1
  web_socket_channel: ^2.2.0
  uuid: ^3.0.7
  modal_bottom_sheet: ^3.0.0-pre
  shared_preferences: ^2.0.18
  app_links: ^3.4.2
  qr_flutter: ^4.0.0
  collection: ^1.17.0
  meta: ^1.8.0
  flutter_html: ^2.2.1
  url_launcher: ^6.1.10
  csv: ^5.0.1
  share_plus: ^6.3.1
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  test: ^1.22.0

flutter:
  uses-material-design: true

  assets:
    - images/
