// ignore_for_file: constant_identifier_names

enum PlanningHostSendCommandType {
  START_SESSION,
  ADD_TICKET,
  SKIP_VOTE,
  REMOVE_PARTICIPANT,
  END_SESSION,
  FINISH_VOTING,
  REVOTE,
  RECONNECT,
  EDIT_TICKET,
  ADD_TIMER,
  CANCEL_TIMER,
  PREVIOUS_TICKETS,
  REQUEST_COFFEE_BREAK,
  START_COFFEE_BREAK_VOTE,
  FINISH_COFFEE_BREAK_VOTE,
  END_COFFEE_BREAK_VOTE,
  COFFEE_BREAK_VOTE,
}
