default_platform(:ios)

APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]
SIGNING_GIT_URL = ENV["SIGNING_GIT_URL"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Push a new build to AppStoreConnect"
  lane :deploy_to_appstore do
    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,            
      duration: 1200,            
      in_house: false
    )

    prepareAppSigning(api_key, TEMP_KEYCHAIN_USER, TEMP_KEYCHAIN_PASSWORD)
    buildReleaseApp(api_key)
    uploadToAppStoreConnect(api_key)
    delete_temp_keychain(TEMP_KEYCHAIN_USER)
  end

  desc "Set up app certificate signing"
  def prepareAppSigning(api_key, keychain_name, keychain_password)
    ensure_temp_keychain(keychain_name, keychain_password)

    match(
      type: 'appstore',
      app_identifier: "za.co.armandkamffer.mamba",
      git_url: SIGNING_GIT_URL,
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      clone_branch_directly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )
  end

  desc "Prepare Flutter environment"
  def prepareFlutter() 
    sh("flutter --version")
    sh("flutter pub get")
  end

  desc "Build appstore archive"
  def buildReleaseApp(api_key)
    increment_build_number(
      build_number: app_store_build_number(
        api_key: api_key,           
        initial_build_number: 0, 
        live: false
        ) + 1
    )

    prepareFlutter()
    cocoapods

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
    )
  end

  desc "Upload archive to AppStoreConnect"
  def uploadToAppStoreConnect(api_key)
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
