default_platform(:ios)

APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Push a new build to AppStoreConntect"
  lane :deploy_to_appstore do

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,            
      duration: 1200,            
      in_house: false
    )

    increment_build_number(
      build_number: app_store_build_number(api_key: api_key, 
                                           initial_build_number: 0, 
                                           live: false) + 1
    )
    
    get_certificates
    
    get_provisioning_profile
    
    build_app(workspace: "Runner.xcworkspace",
              scheme: "Runner",
              include_bitcode: true)
    
    upload_to_testflight(api_key: api_key)
  end
end
