default_platform(:android)

MAMBA_JSON_KEY_DATA = ENV["MAMBA_JSON_KEY_DATA"]

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy_to_google_play do
    buildReleaseApp()
    uploadAppToGooglePlay(MAMBA_JSON_KEY_DATA)
  end

  desc "Build App .aab Bundle"
  def buildReleaseApp()
    prepareFlutter() 
    sh("flutter build appbundle -v")
  end

  desc "Upload App .aab to PlayStore"
  def uploadAppToGooglePlay(json_key_data) 
    supply(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app.aab",
      json_key_data: json_key_data,
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Prepare Flutter environment"
  def prepareFlutter() 
    sh("flutter --version")
    sh("flutter pub get")
  end
end
